---
title: "excercise_2"
author: "chenchunpeng"
date: "2020/3/20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
getwd()
```

```{r}
## Clear object, load data
rm(list = ls())
mydata <- read.csv("data/xy.csv")
```

```{r}
## Check the data relationship, whether it obeys the normal distribution
head(mydata) 
plot(mydata$y ~ mydata$x, data = mydata, main="y ~ x")
par(mfrow=c(1, 2)) 
boxplot(mydata$x, main="x", sub=paste("Outlier rows: ", 
                                      boxplot.stats(mydata$x)$out))# Check outliers
boxplot(mydata$y, main="y", sub=paste("Outlier rows: ", 
                                      boxplot.stats(mydata$y)$out))
```

```{r}
library(e1071)  # Whether to obey the normal distribution
par(mfrow=c(1, 2))  
plot(density(mydata$x), main="Density Plot: x", ylab="Frequency", 
     sub=paste("Skewness:", round(e1071::skewness(mydata$x), 2)))  
polygon(density(mydata$x), col="red")
plot(density(mydata$y), main="Density Plot: y", ylab="Frequency", 
     sub=paste("Skewness:", round(e1071::skewness(cars$dist), 2)))  
polygon(density(mydata$y), col="red")
```

```{r}
## Calculate correlations and build models
cor(mydata$x, mydata$y) 
linearMod <- lm(y ~ x, data= mydata)  
print(linearMod)


summary(linearMod) #summary
```













